=== viktor-petrenko/AAA/src/test/resources/testdata/api/v1/schemas/create-booking-request-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "required": [
    "firstname",
    "lastname",
    "totalprice",
    "depositpaid",
    "bookingdates",
    "additionalneeds"
  ],
  "additionalProperties": false,
  "properties": {
    "firstname": {
      "type": "string",
      "minLength": 1
    },
    "lastname": {
      "type": "string",
      "minLength": 1
    },
    "totalprice": {
      "type": "integer",
      "minimum": 1
    },
    "depositpaid": {
      "type": "boolean"
    },
    "bookingdates": {
      "type": "object",
      "required": [
        "checkin",
        "checkout"
      ],
      "additionalProperties": false,
      "properties": {
        "checkin": {
          "type": "string"
        },
        "checkout": {
          "type": "string"
        }
      }
    },
    "additionalneeds": {
      "type": "string"
    }
  }
}

=== viktor-petrenko/AAA/src/test/resources/testdata/api/v1/booking/booking.json
[
  {
    "firstname": "Iron",
    "lastname": "Man",
    "totalprice": 250,
    "depositpaid": true,
    "bookingdates": {
      "checkin": "2018-01-01",
      "checkout": "2019-01-01"
    },
    "additionalneeds": "Breakfast"
  },
  {
    "firstname": "Captain",
    "lastname": "America",
    "totalprice": 300,
    "depositpaid": false,
    "bookingdates": {
      "checkin": "2026-06-01",
      "checkout": "2026-06-07"
    },
    "additionalneeds": "Dinner"
  },
  {
    "firstname": "Spider",
    "lastname": "Man",
    "totalprice": 1,
    "depositpaid": true,
    "bookingdates": {
      "checkin": "2025-12-01",
      "checkout": "2025-12-02"
    },
    "additionalneeds": "None"
  }
]
